#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdriaAirways
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Adria")]
	public partial class AdriaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCHARTER(CHARTER instance);
    partial void UpdateCHARTER(CHARTER instance);
    partial void DeleteCHARTER(CHARTER instance);
    partial void InsertLETALO(LETALO instance);
    partial void UpdateLETALO(LETALO instance);
    partial void DeleteLETALO(LETALO instance);
    partial void InsertMODEL(MODEL instance);
    partial void UpdateMODEL(MODEL instance);
    partial void DeleteMODEL(MODEL instance);
    partial void InsertPILOT(PILOT instance);
    partial void UpdatePILOT(PILOT instance);
    partial void DeletePILOT(PILOT instance);
    partial void InsertSTRANKA(STRANKA instance);
    partial void UpdateSTRANKA(STRANKA instance);
    partial void DeleteSTRANKA(STRANKA instance);
    partial void InsertZAPOSELNI(ZAPOSELNI instance);
    partial void UpdateZAPOSELNI(ZAPOSELNI instance);
    partial void DeleteZAPOSELNI(ZAPOSELNI instance);
    #endregion
		
		public AdriaDataContext() : 
				base(global::AdriaAirways.Properties.Settings.Default.AdriaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public AdriaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AdriaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AdriaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AdriaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CHARTER> CHARTERs
		{
			get
			{
				return this.GetTable<CHARTER>();
			}
		}
		
		public System.Data.Linq.Table<LETALO> LETALOs
		{
			get
			{
				return this.GetTable<LETALO>();
			}
		}
		
		public System.Data.Linq.Table<MODEL> MODELs
		{
			get
			{
				return this.GetTable<MODEL>();
			}
		}
		
		public System.Data.Linq.Table<PILOT> PILOTs
		{
			get
			{
				return this.GetTable<PILOT>();
			}
		}
		
		public System.Data.Linq.Table<STRANKA> STRANKAs
		{
			get
			{
				return this.GetTable<STRANKA>();
			}
		}
		
		public System.Data.Linq.Table<ZAPOSELNI> ZAPOSELNIs
		{
			get
			{
				return this.GetTable<ZAPOSELNI>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHARTER")]
	public partial class CHARTER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CHAR_POTOVANJE;
		
		private System.Nullable<System.DateTime> _CHAR_DATUM;
		
		private System.Nullable<int> _CHAR_PILOT;
		
		private System.Nullable<int> _CHAR_KOPILOT;
		
		private string _LET_ST;
		
		private string _CHAR_CILJ;
		
		private System.Nullable<float> _CHAR_RAZDALJA;
		
		private System.Nullable<double> _CHAR_UR_LETA;
		
		private System.Nullable<double> _CHAR_UR_ČAKANJA;
		
		private System.Nullable<double> _CHAR_GORIVO_GALLONS;
		
		private System.Nullable<short> _CHAR_NAFTA_QTS;
		
		private System.Nullable<int> _STR_KODA;
		
		private EntityRef<LETALO> _LETALO;
		
		private EntityRef<PILOT> _PILOT;
		
		private EntityRef<STRANKA> _STRANKA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCHAR_POTOVANJEChanging(int value);
    partial void OnCHAR_POTOVANJEChanged();
    partial void OnCHAR_DATUMChanging(System.Nullable<System.DateTime> value);
    partial void OnCHAR_DATUMChanged();
    partial void OnCHAR_PILOTChanging(System.Nullable<int> value);
    partial void OnCHAR_PILOTChanged();
    partial void OnCHAR_KOPILOTChanging(System.Nullable<int> value);
    partial void OnCHAR_KOPILOTChanged();
    partial void OnLET_STChanging(string value);
    partial void OnLET_STChanged();
    partial void OnCHAR_CILJChanging(string value);
    partial void OnCHAR_CILJChanged();
    partial void OnCHAR_RAZDALJAChanging(System.Nullable<float> value);
    partial void OnCHAR_RAZDALJAChanged();
    partial void OnCHAR_UR_LETAChanging(System.Nullable<double> value);
    partial void OnCHAR_UR_LETAChanged();
    partial void OnCHAR_UR_ČAKANJAChanging(System.Nullable<double> value);
    partial void OnCHAR_UR_ČAKANJAChanged();
    partial void OnCHAR_GORIVO_GALLONSChanging(System.Nullable<double> value);
    partial void OnCHAR_GORIVO_GALLONSChanged();
    partial void OnCHAR_NAFTA_QTSChanging(System.Nullable<short> value);
    partial void OnCHAR_NAFTA_QTSChanged();
    partial void OnSTR_KODAChanging(System.Nullable<int> value);
    partial void OnSTR_KODAChanged();
    #endregion
		
		public CHARTER()
		{
			this._LETALO = default(EntityRef<LETALO>);
			this._PILOT = default(EntityRef<PILOT>);
			this._STRANKA = default(EntityRef<STRANKA>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHAR_POTOVANJE", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CHAR_POTOVANJE
		{
			get
			{
				return this._CHAR_POTOVANJE;
			}
			set
			{
				if ((this._CHAR_POTOVANJE != value))
				{
					this.OnCHAR_POTOVANJEChanging(value);
					this.SendPropertyChanging();
					this._CHAR_POTOVANJE = value;
					this.SendPropertyChanged("CHAR_POTOVANJE");
					this.OnCHAR_POTOVANJEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHAR_DATUM", DbType="DateTime")]
		public System.Nullable<System.DateTime> CHAR_DATUM
		{
			get
			{
				return this._CHAR_DATUM;
			}
			set
			{
				if ((this._CHAR_DATUM != value))
				{
					this.OnCHAR_DATUMChanging(value);
					this.SendPropertyChanging();
					this._CHAR_DATUM = value;
					this.SendPropertyChanged("CHAR_DATUM");
					this.OnCHAR_DATUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHAR_PILOT", DbType="Int")]
		public System.Nullable<int> CHAR_PILOT
		{
			get
			{
				return this._CHAR_PILOT;
			}
			set
			{
				if ((this._CHAR_PILOT != value))
				{
					if (this._PILOT.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCHAR_PILOTChanging(value);
					this.SendPropertyChanging();
					this._CHAR_PILOT = value;
					this.SendPropertyChanged("CHAR_PILOT");
					this.OnCHAR_PILOTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHAR_KOPILOT", DbType="Int")]
		public System.Nullable<int> CHAR_KOPILOT
		{
			get
			{
				return this._CHAR_KOPILOT;
			}
			set
			{
				if ((this._CHAR_KOPILOT != value))
				{
					this.OnCHAR_KOPILOTChanging(value);
					this.SendPropertyChanging();
					this._CHAR_KOPILOT = value;
					this.SendPropertyChanged("CHAR_KOPILOT");
					this.OnCHAR_KOPILOTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LET_ST", DbType="NVarChar(5)")]
		public string LET_ST
		{
			get
			{
				return this._LET_ST;
			}
			set
			{
				if ((this._LET_ST != value))
				{
					if (this._LETALO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnLET_STChanging(value);
					this.SendPropertyChanging();
					this._LET_ST = value;
					this.SendPropertyChanged("LET_ST");
					this.OnLET_STChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHAR_CILJ", DbType="NVarChar(3)")]
		public string CHAR_CILJ
		{
			get
			{
				return this._CHAR_CILJ;
			}
			set
			{
				if ((this._CHAR_CILJ != value))
				{
					this.OnCHAR_CILJChanging(value);
					this.SendPropertyChanging();
					this._CHAR_CILJ = value;
					this.SendPropertyChanged("CHAR_CILJ");
					this.OnCHAR_CILJChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHAR_RAZDALJA", DbType="Real")]
		public System.Nullable<float> CHAR_RAZDALJA
		{
			get
			{
				return this._CHAR_RAZDALJA;
			}
			set
			{
				if ((this._CHAR_RAZDALJA != value))
				{
					this.OnCHAR_RAZDALJAChanging(value);
					this.SendPropertyChanging();
					this._CHAR_RAZDALJA = value;
					this.SendPropertyChanged("CHAR_RAZDALJA");
					this.OnCHAR_RAZDALJAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHAR_UR_LETA", DbType="Float")]
		public System.Nullable<double> CHAR_UR_LETA
		{
			get
			{
				return this._CHAR_UR_LETA;
			}
			set
			{
				if ((this._CHAR_UR_LETA != value))
				{
					this.OnCHAR_UR_LETAChanging(value);
					this.SendPropertyChanging();
					this._CHAR_UR_LETA = value;
					this.SendPropertyChanged("CHAR_UR_LETA");
					this.OnCHAR_UR_LETAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHAR_UR_ČAKANJA", DbType="Float")]
		public System.Nullable<double> CHAR_UR_ČAKANJA
		{
			get
			{
				return this._CHAR_UR_ČAKANJA;
			}
			set
			{
				if ((this._CHAR_UR_ČAKANJA != value))
				{
					this.OnCHAR_UR_ČAKANJAChanging(value);
					this.SendPropertyChanging();
					this._CHAR_UR_ČAKANJA = value;
					this.SendPropertyChanged("CHAR_UR_ČAKANJA");
					this.OnCHAR_UR_ČAKANJAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHAR_GORIVO_GALLONS", DbType="Float")]
		public System.Nullable<double> CHAR_GORIVO_GALLONS
		{
			get
			{
				return this._CHAR_GORIVO_GALLONS;
			}
			set
			{
				if ((this._CHAR_GORIVO_GALLONS != value))
				{
					this.OnCHAR_GORIVO_GALLONSChanging(value);
					this.SendPropertyChanging();
					this._CHAR_GORIVO_GALLONS = value;
					this.SendPropertyChanged("CHAR_GORIVO_GALLONS");
					this.OnCHAR_GORIVO_GALLONSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHAR_NAFTA_QTS", DbType="SmallInt")]
		public System.Nullable<short> CHAR_NAFTA_QTS
		{
			get
			{
				return this._CHAR_NAFTA_QTS;
			}
			set
			{
				if ((this._CHAR_NAFTA_QTS != value))
				{
					this.OnCHAR_NAFTA_QTSChanging(value);
					this.SendPropertyChanging();
					this._CHAR_NAFTA_QTS = value;
					this.SendPropertyChanged("CHAR_NAFTA_QTS");
					this.OnCHAR_NAFTA_QTSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STR_KODA", DbType="Int")]
		public System.Nullable<int> STR_KODA
		{
			get
			{
				return this._STR_KODA;
			}
			set
			{
				if ((this._STR_KODA != value))
				{
					if (this._STRANKA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSTR_KODAChanging(value);
					this.SendPropertyChanging();
					this._STR_KODA = value;
					this.SendPropertyChanged("STR_KODA");
					this.OnSTR_KODAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LETALO_CHARTER", Storage="_LETALO", ThisKey="LET_ST", OtherKey="LET_ST", IsForeignKey=true, DeleteRule="CASCADE")]
		public LETALO LETALO
		{
			get
			{
				return this._LETALO.Entity;
			}
			set
			{
				LETALO previousValue = this._LETALO.Entity;
				if (((previousValue != value) 
							|| (this._LETALO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LETALO.Entity = null;
						previousValue.CHARTERs.Remove(this);
					}
					this._LETALO.Entity = value;
					if ((value != null))
					{
						value.CHARTERs.Add(this);
						this._LET_ST = value.LET_ST;
					}
					else
					{
						this._LET_ST = default(string);
					}
					this.SendPropertyChanged("LETALO");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PILOT_CHARTER", Storage="_PILOT", ThisKey="CHAR_PILOT", OtherKey="ZAP_ST", IsForeignKey=true, DeleteRule="CASCADE")]
		public PILOT PILOT
		{
			get
			{
				return this._PILOT.Entity;
			}
			set
			{
				PILOT previousValue = this._PILOT.Entity;
				if (((previousValue != value) 
							|| (this._PILOT.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PILOT.Entity = null;
						previousValue.CHARTERs.Remove(this);
					}
					this._PILOT.Entity = value;
					if ((value != null))
					{
						value.CHARTERs.Add(this);
						this._CHAR_PILOT = value.ZAP_ST;
					}
					else
					{
						this._CHAR_PILOT = default(Nullable<int>);
					}
					this.SendPropertyChanged("PILOT");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="STRANKA_CHARTER", Storage="_STRANKA", ThisKey="STR_KODA", OtherKey="STR_KODA", IsForeignKey=true, DeleteRule="CASCADE")]
		public STRANKA STRANKA
		{
			get
			{
				return this._STRANKA.Entity;
			}
			set
			{
				STRANKA previousValue = this._STRANKA.Entity;
				if (((previousValue != value) 
							|| (this._STRANKA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._STRANKA.Entity = null;
						previousValue.CHARTERs.Remove(this);
					}
					this._STRANKA.Entity = value;
					if ((value != null))
					{
						value.CHARTERs.Add(this);
						this._STR_KODA = value.STR_KODA;
					}
					else
					{
						this._STR_KODA = default(Nullable<int>);
					}
					this.SendPropertyChanged("STRANKA");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LETALO")]
	public partial class LETALO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _LET_ST;
		
		private string _MOD_KODA;
		
		private System.Nullable<double> _AC_TTAF;
		
		private System.Nullable<double> _AC_TTEL;
		
		private System.Nullable<double> _AC_TTER;
		
		private EntitySet<CHARTER> _CHARTERs;
		
		private EntityRef<MODEL> _MODEL;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLET_STChanging(string value);
    partial void OnLET_STChanged();
    partial void OnMOD_KODAChanging(string value);
    partial void OnMOD_KODAChanged();
    partial void OnAC_TTAFChanging(System.Nullable<double> value);
    partial void OnAC_TTAFChanged();
    partial void OnAC_TTELChanging(System.Nullable<double> value);
    partial void OnAC_TTELChanged();
    partial void OnAC_TTERChanging(System.Nullable<double> value);
    partial void OnAC_TTERChanged();
    #endregion
		
		public LETALO()
		{
			this._CHARTERs = new EntitySet<CHARTER>(new Action<CHARTER>(this.attach_CHARTERs), new Action<CHARTER>(this.detach_CHARTERs));
			this._MODEL = default(EntityRef<MODEL>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LET_ST", DbType="NVarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string LET_ST
		{
			get
			{
				return this._LET_ST;
			}
			set
			{
				if ((this._LET_ST != value))
				{
					this.OnLET_STChanging(value);
					this.SendPropertyChanging();
					this._LET_ST = value;
					this.SendPropertyChanged("LET_ST");
					this.OnLET_STChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOD_KODA", DbType="NVarChar(10)")]
		public string MOD_KODA
		{
			get
			{
				return this._MOD_KODA;
			}
			set
			{
				if ((this._MOD_KODA != value))
				{
					if (this._MODEL.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMOD_KODAChanging(value);
					this.SendPropertyChanging();
					this._MOD_KODA = value;
					this.SendPropertyChanged("MOD_KODA");
					this.OnMOD_KODAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AC_TTAF", DbType="Float")]
		public System.Nullable<double> AC_TTAF
		{
			get
			{
				return this._AC_TTAF;
			}
			set
			{
				if ((this._AC_TTAF != value))
				{
					this.OnAC_TTAFChanging(value);
					this.SendPropertyChanging();
					this._AC_TTAF = value;
					this.SendPropertyChanged("AC_TTAF");
					this.OnAC_TTAFChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AC_TTEL", DbType="Float")]
		public System.Nullable<double> AC_TTEL
		{
			get
			{
				return this._AC_TTEL;
			}
			set
			{
				if ((this._AC_TTEL != value))
				{
					this.OnAC_TTELChanging(value);
					this.SendPropertyChanging();
					this._AC_TTEL = value;
					this.SendPropertyChanged("AC_TTEL");
					this.OnAC_TTELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AC_TTER", DbType="Float")]
		public System.Nullable<double> AC_TTER
		{
			get
			{
				return this._AC_TTER;
			}
			set
			{
				if ((this._AC_TTER != value))
				{
					this.OnAC_TTERChanging(value);
					this.SendPropertyChanging();
					this._AC_TTER = value;
					this.SendPropertyChanged("AC_TTER");
					this.OnAC_TTERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LETALO_CHARTER", Storage="_CHARTERs", ThisKey="LET_ST", OtherKey="LET_ST")]
		public EntitySet<CHARTER> CHARTERs
		{
			get
			{
				return this._CHARTERs;
			}
			set
			{
				this._CHARTERs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MODEL_LETALO", Storage="_MODEL", ThisKey="MOD_KODA", OtherKey="MOD_KODA", IsForeignKey=true, DeleteRule="CASCADE")]
		public MODEL MODEL
		{
			get
			{
				return this._MODEL.Entity;
			}
			set
			{
				MODEL previousValue = this._MODEL.Entity;
				if (((previousValue != value) 
							|| (this._MODEL.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MODEL.Entity = null;
						previousValue.LETALOs.Remove(this);
					}
					this._MODEL.Entity = value;
					if ((value != null))
					{
						value.LETALOs.Add(this);
						this._MOD_KODA = value.MOD_KODA;
					}
					else
					{
						this._MOD_KODA = default(string);
					}
					this.SendPropertyChanged("MODEL");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHARTERs(CHARTER entity)
		{
			this.SendPropertyChanging();
			entity.LETALO = this;
		}
		
		private void detach_CHARTERs(CHARTER entity)
		{
			this.SendPropertyChanging();
			entity.LETALO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MODEL")]
	public partial class MODEL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MOD_KODA;
		
		private string _MOD_PROIZVAJALEC;
		
		private string _MOD_IME;
		
		private System.Nullable<double> _MOD_SEDEŽEV;
		
		private System.Nullable<decimal> _MOD_NA_MILJO;
		
		private EntitySet<LETALO> _LETALOs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMOD_KODAChanging(string value);
    partial void OnMOD_KODAChanged();
    partial void OnMOD_PROIZVAJALECChanging(string value);
    partial void OnMOD_PROIZVAJALECChanged();
    partial void OnMOD_IMEChanging(string value);
    partial void OnMOD_IMEChanged();
    partial void OnMOD_SEDEŽEVChanging(System.Nullable<double> value);
    partial void OnMOD_SEDEŽEVChanged();
    partial void OnMOD_NA_MILJOChanging(System.Nullable<decimal> value);
    partial void OnMOD_NA_MILJOChanged();
    #endregion
		
		public MODEL()
		{
			this._LETALOs = new EntitySet<LETALO>(new Action<LETALO>(this.attach_LETALOs), new Action<LETALO>(this.detach_LETALOs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOD_KODA", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MOD_KODA
		{
			get
			{
				return this._MOD_KODA;
			}
			set
			{
				if ((this._MOD_KODA != value))
				{
					this.OnMOD_KODAChanging(value);
					this.SendPropertyChanging();
					this._MOD_KODA = value;
					this.SendPropertyChanged("MOD_KODA");
					this.OnMOD_KODAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOD_PROIZVAJALEC", DbType="NVarChar(15)")]
		public string MOD_PROIZVAJALEC
		{
			get
			{
				return this._MOD_PROIZVAJALEC;
			}
			set
			{
				if ((this._MOD_PROIZVAJALEC != value))
				{
					this.OnMOD_PROIZVAJALECChanging(value);
					this.SendPropertyChanging();
					this._MOD_PROIZVAJALEC = value;
					this.SendPropertyChanged("MOD_PROIZVAJALEC");
					this.OnMOD_PROIZVAJALECChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOD_IME", DbType="NVarChar(20)")]
		public string MOD_IME
		{
			get
			{
				return this._MOD_IME;
			}
			set
			{
				if ((this._MOD_IME != value))
				{
					this.OnMOD_IMEChanging(value);
					this.SendPropertyChanging();
					this._MOD_IME = value;
					this.SendPropertyChanged("MOD_IME");
					this.OnMOD_IMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOD_SEDEŽEV", DbType="Float")]
		public System.Nullable<double> MOD_SEDEŽEV
		{
			get
			{
				return this._MOD_SEDEŽEV;
			}
			set
			{
				if ((this._MOD_SEDEŽEV != value))
				{
					this.OnMOD_SEDEŽEVChanging(value);
					this.SendPropertyChanging();
					this._MOD_SEDEŽEV = value;
					this.SendPropertyChanged("MOD_SEDEŽEV");
					this.OnMOD_SEDEŽEVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOD_NA_MILJO", DbType="Money")]
		public System.Nullable<decimal> MOD_NA_MILJO
		{
			get
			{
				return this._MOD_NA_MILJO;
			}
			set
			{
				if ((this._MOD_NA_MILJO != value))
				{
					this.OnMOD_NA_MILJOChanging(value);
					this.SendPropertyChanging();
					this._MOD_NA_MILJO = value;
					this.SendPropertyChanged("MOD_NA_MILJO");
					this.OnMOD_NA_MILJOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MODEL_LETALO", Storage="_LETALOs", ThisKey="MOD_KODA", OtherKey="MOD_KODA")]
		public EntitySet<LETALO> LETALOs
		{
			get
			{
				return this._LETALOs;
			}
			set
			{
				this._LETALOs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LETALOs(LETALO entity)
		{
			this.SendPropertyChanging();
			entity.MODEL = this;
		}
		
		private void detach_LETALOs(LETALO entity)
		{
			this.SendPropertyChanging();
			entity.MODEL = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PILOT")]
	public partial class PILOT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ZAP_ST;
		
		private string _PIL_LICENCA;
		
		private string _PIL_KVAL;
		
		private string _PIL_MED_TIP;
		
		private System.Nullable<System.DateTime> _PIL_MED_DATUM;
		
		private System.Nullable<System.DateTime> _PIL_PT135_DATUM;
		
		private EntitySet<CHARTER> _CHARTERs;
		
		private EntityRef<ZAPOSELNI> _ZAPOSELNI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnZAP_STChanging(int value);
    partial void OnZAP_STChanged();
    partial void OnPIL_LICENCAChanging(string value);
    partial void OnPIL_LICENCAChanged();
    partial void OnPIL_KVALChanging(string value);
    partial void OnPIL_KVALChanged();
    partial void OnPIL_MED_TIPChanging(string value);
    partial void OnPIL_MED_TIPChanged();
    partial void OnPIL_MED_DATUMChanging(System.Nullable<System.DateTime> value);
    partial void OnPIL_MED_DATUMChanged();
    partial void OnPIL_PT135_DATUMChanging(System.Nullable<System.DateTime> value);
    partial void OnPIL_PT135_DATUMChanged();
    #endregion
		
		public PILOT()
		{
			this._CHARTERs = new EntitySet<CHARTER>(new Action<CHARTER>(this.attach_CHARTERs), new Action<CHARTER>(this.detach_CHARTERs));
			this._ZAPOSELNI = default(EntityRef<ZAPOSELNI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZAP_ST", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ZAP_ST
		{
			get
			{
				return this._ZAP_ST;
			}
			set
			{
				if ((this._ZAP_ST != value))
				{
					if (this._ZAPOSELNI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnZAP_STChanging(value);
					this.SendPropertyChanging();
					this._ZAP_ST = value;
					this.SendPropertyChanged("ZAP_ST");
					this.OnZAP_STChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PIL_LICENCA", DbType="NVarChar(25)")]
		public string PIL_LICENCA
		{
			get
			{
				return this._PIL_LICENCA;
			}
			set
			{
				if ((this._PIL_LICENCA != value))
				{
					this.OnPIL_LICENCAChanging(value);
					this.SendPropertyChanging();
					this._PIL_LICENCA = value;
					this.SendPropertyChanged("PIL_LICENCA");
					this.OnPIL_LICENCAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PIL_KVAL", DbType="NVarChar(30)")]
		public string PIL_KVAL
		{
			get
			{
				return this._PIL_KVAL;
			}
			set
			{
				if ((this._PIL_KVAL != value))
				{
					this.OnPIL_KVALChanging(value);
					this.SendPropertyChanging();
					this._PIL_KVAL = value;
					this.SendPropertyChanged("PIL_KVAL");
					this.OnPIL_KVALChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PIL_MED_TIP", DbType="NVarChar(1)")]
		public string PIL_MED_TIP
		{
			get
			{
				return this._PIL_MED_TIP;
			}
			set
			{
				if ((this._PIL_MED_TIP != value))
				{
					this.OnPIL_MED_TIPChanging(value);
					this.SendPropertyChanging();
					this._PIL_MED_TIP = value;
					this.SendPropertyChanged("PIL_MED_TIP");
					this.OnPIL_MED_TIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PIL_MED_DATUM", DbType="DateTime")]
		public System.Nullable<System.DateTime> PIL_MED_DATUM
		{
			get
			{
				return this._PIL_MED_DATUM;
			}
			set
			{
				if ((this._PIL_MED_DATUM != value))
				{
					this.OnPIL_MED_DATUMChanging(value);
					this.SendPropertyChanging();
					this._PIL_MED_DATUM = value;
					this.SendPropertyChanged("PIL_MED_DATUM");
					this.OnPIL_MED_DATUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PIL_PT135_DATUM", DbType="DateTime")]
		public System.Nullable<System.DateTime> PIL_PT135_DATUM
		{
			get
			{
				return this._PIL_PT135_DATUM;
			}
			set
			{
				if ((this._PIL_PT135_DATUM != value))
				{
					this.OnPIL_PT135_DATUMChanging(value);
					this.SendPropertyChanging();
					this._PIL_PT135_DATUM = value;
					this.SendPropertyChanged("PIL_PT135_DATUM");
					this.OnPIL_PT135_DATUMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PILOT_CHARTER", Storage="_CHARTERs", ThisKey="ZAP_ST", OtherKey="CHAR_PILOT")]
		public EntitySet<CHARTER> CHARTERs
		{
			get
			{
				return this._CHARTERs;
			}
			set
			{
				this._CHARTERs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ZAPOSELNI_PILOT", Storage="_ZAPOSELNI", ThisKey="ZAP_ST", OtherKey="ZAP_ST", IsForeignKey=true)]
		public ZAPOSELNI ZAPOSELNI
		{
			get
			{
				return this._ZAPOSELNI.Entity;
			}
			set
			{
				ZAPOSELNI previousValue = this._ZAPOSELNI.Entity;
				if (((previousValue != value) 
							|| (this._ZAPOSELNI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ZAPOSELNI.Entity = null;
						previousValue.PILOT = null;
					}
					this._ZAPOSELNI.Entity = value;
					if ((value != null))
					{
						value.PILOT = this;
						this._ZAP_ST = value.ZAP_ST;
					}
					else
					{
						this._ZAP_ST = default(int);
					}
					this.SendPropertyChanged("ZAPOSELNI");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHARTERs(CHARTER entity)
		{
			this.SendPropertyChanging();
			entity.PILOT = this;
		}
		
		private void detach_CHARTERs(CHARTER entity)
		{
			this.SendPropertyChanging();
			entity.PILOT = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.STRANKA")]
	public partial class STRANKA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _STR_KODA;
		
		private string _STR_PRIIMEK;
		
		private string _STR_IME;
		
		private string _STR_ZAČ;
		
		private string _STR_POŠTA;
		
		private string _STR_TELEFON;
		
		private System.Nullable<decimal> _STR_STANJE;
		
		private EntitySet<CHARTER> _CHARTERs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTR_KODAChanging(int value);
    partial void OnSTR_KODAChanged();
    partial void OnSTR_PRIIMEKChanging(string value);
    partial void OnSTR_PRIIMEKChanged();
    partial void OnSTR_IMEChanging(string value);
    partial void OnSTR_IMEChanged();
    partial void OnSTR_ZAČChanging(string value);
    partial void OnSTR_ZAČChanged();
    partial void OnSTR_POŠTAChanging(string value);
    partial void OnSTR_POŠTAChanged();
    partial void OnSTR_TELEFONChanging(string value);
    partial void OnSTR_TELEFONChanged();
    partial void OnSTR_STANJEChanging(System.Nullable<decimal> value);
    partial void OnSTR_STANJEChanged();
    #endregion
		
		public STRANKA()
		{
			this._CHARTERs = new EntitySet<CHARTER>(new Action<CHARTER>(this.attach_CHARTERs), new Action<CHARTER>(this.detach_CHARTERs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STR_KODA", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int STR_KODA
		{
			get
			{
				return this._STR_KODA;
			}
			set
			{
				if ((this._STR_KODA != value))
				{
					this.OnSTR_KODAChanging(value);
					this.SendPropertyChanging();
					this._STR_KODA = value;
					this.SendPropertyChanged("STR_KODA");
					this.OnSTR_KODAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STR_PRIIMEK", DbType="NVarChar(15)")]
		public string STR_PRIIMEK
		{
			get
			{
				return this._STR_PRIIMEK;
			}
			set
			{
				if ((this._STR_PRIIMEK != value))
				{
					this.OnSTR_PRIIMEKChanging(value);
					this.SendPropertyChanging();
					this._STR_PRIIMEK = value;
					this.SendPropertyChanged("STR_PRIIMEK");
					this.OnSTR_PRIIMEKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STR_IME", DbType="NVarChar(15)")]
		public string STR_IME
		{
			get
			{
				return this._STR_IME;
			}
			set
			{
				if ((this._STR_IME != value))
				{
					this.OnSTR_IMEChanging(value);
					this.SendPropertyChanging();
					this._STR_IME = value;
					this.SendPropertyChanged("STR_IME");
					this.OnSTR_IMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STR_ZAČ", DbType="NVarChar(1)")]
		public string STR_ZAČ
		{
			get
			{
				return this._STR_ZAČ;
			}
			set
			{
				if ((this._STR_ZAČ != value))
				{
					this.OnSTR_ZAČChanging(value);
					this.SendPropertyChanging();
					this._STR_ZAČ = value;
					this.SendPropertyChanged("STR_ZAČ");
					this.OnSTR_ZAČChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STR_POŠTA", DbType="NVarChar(3)")]
		public string STR_POŠTA
		{
			get
			{
				return this._STR_POŠTA;
			}
			set
			{
				if ((this._STR_POŠTA != value))
				{
					this.OnSTR_POŠTAChanging(value);
					this.SendPropertyChanging();
					this._STR_POŠTA = value;
					this.SendPropertyChanged("STR_POŠTA");
					this.OnSTR_POŠTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STR_TELEFON", DbType="NVarChar(8)")]
		public string STR_TELEFON
		{
			get
			{
				return this._STR_TELEFON;
			}
			set
			{
				if ((this._STR_TELEFON != value))
				{
					this.OnSTR_TELEFONChanging(value);
					this.SendPropertyChanging();
					this._STR_TELEFON = value;
					this.SendPropertyChanged("STR_TELEFON");
					this.OnSTR_TELEFONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STR_STANJE", DbType="Money")]
		public System.Nullable<decimal> STR_STANJE
		{
			get
			{
				return this._STR_STANJE;
			}
			set
			{
				if ((this._STR_STANJE != value))
				{
					this.OnSTR_STANJEChanging(value);
					this.SendPropertyChanging();
					this._STR_STANJE = value;
					this.SendPropertyChanged("STR_STANJE");
					this.OnSTR_STANJEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="STRANKA_CHARTER", Storage="_CHARTERs", ThisKey="STR_KODA", OtherKey="STR_KODA")]
		public EntitySet<CHARTER> CHARTERs
		{
			get
			{
				return this._CHARTERs;
			}
			set
			{
				this._CHARTERs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHARTERs(CHARTER entity)
		{
			this.SendPropertyChanging();
			entity.STRANKA = this;
		}
		
		private void detach_CHARTERs(CHARTER entity)
		{
			this.SendPropertyChanging();
			entity.STRANKA = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ZAPOSELNI")]
	public partial class ZAPOSELNI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ZAP_ST;
		
		private string _ZAP_NAZIV;
		
		private string _ZAP_PRIIMEK;
		
		private string _ZAP_IME;
		
		private string _ZAP_ZAČ;
		
		private System.Nullable<System.DateTime> _ZAP_DR;
		
		private System.Nullable<System.DateTime> _ZAP_DATUM_ZAP;
		
		private EntityRef<PILOT> _PILOT;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnZAP_STChanging(int value);
    partial void OnZAP_STChanged();
    partial void OnZAP_NAZIVChanging(string value);
    partial void OnZAP_NAZIVChanged();
    partial void OnZAP_PRIIMEKChanging(string value);
    partial void OnZAP_PRIIMEKChanged();
    partial void OnZAP_IMEChanging(string value);
    partial void OnZAP_IMEChanged();
    partial void OnZAP_ZAČChanging(string value);
    partial void OnZAP_ZAČChanged();
    partial void OnZAP_DRChanging(System.Nullable<System.DateTime> value);
    partial void OnZAP_DRChanged();
    partial void OnZAP_DATUM_ZAPChanging(System.Nullable<System.DateTime> value);
    partial void OnZAP_DATUM_ZAPChanged();
    #endregion
		
		public ZAPOSELNI()
		{
			this._PILOT = default(EntityRef<PILOT>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZAP_ST", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ZAP_ST
		{
			get
			{
				return this._ZAP_ST;
			}
			set
			{
				if ((this._ZAP_ST != value))
				{
					this.OnZAP_STChanging(value);
					this.SendPropertyChanging();
					this._ZAP_ST = value;
					this.SendPropertyChanged("ZAP_ST");
					this.OnZAP_STChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZAP_NAZIV", DbType="NVarChar(4) NOT NULL", CanBeNull=false)]
		public string ZAP_NAZIV
		{
			get
			{
				return this._ZAP_NAZIV;
			}
			set
			{
				if ((this._ZAP_NAZIV != value))
				{
					this.OnZAP_NAZIVChanging(value);
					this.SendPropertyChanging();
					this._ZAP_NAZIV = value;
					this.SendPropertyChanged("ZAP_NAZIV");
					this.OnZAP_NAZIVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZAP_PRIIMEK", DbType="NVarChar(15)")]
		public string ZAP_PRIIMEK
		{
			get
			{
				return this._ZAP_PRIIMEK;
			}
			set
			{
				if ((this._ZAP_PRIIMEK != value))
				{
					this.OnZAP_PRIIMEKChanging(value);
					this.SendPropertyChanging();
					this._ZAP_PRIIMEK = value;
					this.SendPropertyChanged("ZAP_PRIIMEK");
					this.OnZAP_PRIIMEKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZAP_IME", DbType="NVarChar(15)")]
		public string ZAP_IME
		{
			get
			{
				return this._ZAP_IME;
			}
			set
			{
				if ((this._ZAP_IME != value))
				{
					this.OnZAP_IMEChanging(value);
					this.SendPropertyChanging();
					this._ZAP_IME = value;
					this.SendPropertyChanged("ZAP_IME");
					this.OnZAP_IMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZAP_ZAČ", DbType="NVarChar(1)")]
		public string ZAP_ZAČ
		{
			get
			{
				return this._ZAP_ZAČ;
			}
			set
			{
				if ((this._ZAP_ZAČ != value))
				{
					this.OnZAP_ZAČChanging(value);
					this.SendPropertyChanging();
					this._ZAP_ZAČ = value;
					this.SendPropertyChanged("ZAP_ZAČ");
					this.OnZAP_ZAČChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZAP_DR", DbType="DateTime")]
		public System.Nullable<System.DateTime> ZAP_DR
		{
			get
			{
				return this._ZAP_DR;
			}
			set
			{
				if ((this._ZAP_DR != value))
				{
					this.OnZAP_DRChanging(value);
					this.SendPropertyChanging();
					this._ZAP_DR = value;
					this.SendPropertyChanged("ZAP_DR");
					this.OnZAP_DRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ZAP_DATUM_ZAP", DbType="DateTime")]
		public System.Nullable<System.DateTime> ZAP_DATUM_ZAP
		{
			get
			{
				return this._ZAP_DATUM_ZAP;
			}
			set
			{
				if ((this._ZAP_DATUM_ZAP != value))
				{
					this.OnZAP_DATUM_ZAPChanging(value);
					this.SendPropertyChanging();
					this._ZAP_DATUM_ZAP = value;
					this.SendPropertyChanged("ZAP_DATUM_ZAP");
					this.OnZAP_DATUM_ZAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ZAPOSELNI_PILOT", Storage="_PILOT", ThisKey="ZAP_ST", OtherKey="ZAP_ST", IsUnique=true, IsForeignKey=false)]
		public PILOT PILOT
		{
			get
			{
				return this._PILOT.Entity;
			}
			set
			{
				PILOT previousValue = this._PILOT.Entity;
				if (((previousValue != value) 
							|| (this._PILOT.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PILOT.Entity = null;
						previousValue.ZAPOSELNI = null;
					}
					this._PILOT.Entity = value;
					if ((value != null))
					{
						value.ZAPOSELNI = this;
					}
					this.SendPropertyChanged("PILOT");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
